/*
==========================================================
Project: SQL Practice – Starlink Analytics
Task: ST-534

Title:
Country Revenue Concentration

Author:
Pavlo Kotenko

Version:
1.0

Description:

Calculate each user's monthly revenue after applying
the subscription discount.

For each user, calculate the total monthly revenue
generated by their country and determine what percentage
of the country's total revenue comes from that user.

Monthly revenue:

monthly_fee * (1 - discount_percent / 100.0)

Revenue share:

user_monthly_revenue
/
country_total_revenue * 100

Return only users whose revenue share is greater than 10%.

Sort the results by revenue share in descending order.

Display:

- first_name
- last_name
- country
- monthly_revenue
- country_total_revenue
- revenue_share_percent

Round:

- revenue_share_percent to 2 decimal places

Topics:

- JOIN
- CTE
- GROUP BY
- SUM()
- CROSS JOIN / CTE JOIN
- Calculated Fields
- WHERE
- ROUND()
- Sorting

Expected Result:

first_name
last_name
country
monthly_revenue
country_total_revenue
revenue_share_percent

==========================================================
*/

WITH user_revenue AS (
SELECT
sc.first_name,
sc.last_name,
sc.country,
(s.monthly_fee * (1 - (s.discount_percent / 100.0))) AS monthly_revenue_by_user
FROM starlink_customers sc
JOIN subscriptions s 
ON sc.unique_id = s.customer_id 
),
total_monthly_revenue AS (
SELECT
sc.country,
SUM((s.monthly_fee * (1 - (s.discount_percent / 100.0)))) AS monthly_revenue_by_country
FROM starlink_customers sc
JOIN subscriptions s 
ON sc.unique_id = s.customer_id
GROUP BY sc.country 
)
SELECT
u.first_name,
u.last_name,
u.country,
u.monthly_revenue_by_user AS monthly_revenue,
t.monthly_revenue_by_country AS country_total_revenue,
ROUND(((u.monthly_revenue_by_user / t.monthly_revenue_by_country) * 100.0),2) AS revenue_share_percent
FROM user_revenue u
LEFT JOIN total_monthly_revenue t
ON t.country = u.country 
ORDER BY revenue_share_percent DESC;
































