/*
==========================================================
Project: SQL Practice – Starlink Analytics
Task: ST-549

Title:
Country Revenue Ranking

Author:
Pavlo Kotenko

Version:
1.0

Description:

Determine which countries are the leaders in revenue
efficiency based on average monthly revenue per user.

For each country calculate:

- country
- users_count
- total_monthly_revenue
- average_revenue_per_user
- country_rank

Monthly revenue for each user should be calculated as:

monthly_fee * (1 - discount_percent / 100.0)

Country metrics:

- users_count — number of users in the country
- total_monthly_revenue — total discounted monthly revenue
  generated by all users in the country
- average_revenue_per_user — average discounted monthly
  revenue per user in the country
- country_rank — ranking of the country based on
  average_revenue_per_user

Include only countries with at least 20 users.

Rank all eligible countries by average_revenue_per_user
in descending order.

Countries with the same average revenue per user should
receive the same rank. The next rank after a tie should
contain a gap.

Example:

1
2
2
4

Use RANK() for calculating the country rank.

Round monetary values to 2 decimal places.

Sort the final result by country_rank in ascending order.

Display:

- country
- users_count
- total_monthly_revenue
- average_revenue_per_user
- country_rank

Topics:

- CTE
- JOIN
- GROUP BY
- COUNT
- SUM
- HAVING
- RANK
- Window Functions
- Calculated fields
- ROUND
- Filtering
- ORDER BY
==========================================================
*/

WITH statistic_by_country AS (
SELECT 
sc.country,
COUNT(*) AS users_count,
SUM(s.monthly_fee * (1 - (s.discount_percent / 100.0))) AS total_monthly_revenue,
AVG(s.monthly_fee * (1 - (s.discount_percent / 100.0))) AS average_revenue_per_user
FROM starlink_customers sc
JOIN subscriptions s 
ON sc.unique_id = s.customer_id
GROUP BY sc.country 
HAVING COUNT(*) >= 20
),
rank_by_country AS (
SELECT *,
RANK() OVER (
ORDER BY average_revenue_per_user DESC
) AS country_rank 
FROM statistic_by_country 
)
SELECT 
country,
users_count,
total_monthly_revenue,
ROUND(average_revenue_per_user,2) AS average_revenue_per_user,
country_rank
FROM rank_by_country  
ORDER BY country_rank ASC





























