/*
==========================================================
Project: SQL Practice – Starlink Analytics
Task: ST-550

Title:
Country Revenue Gap

Author:
Pavlo Kotenko

Version:
1.0

Description:

Determine how much the average monthly revenue per user
differs between neighboring countries in the revenue ranking.

For each country calculate:

- country
- users_count
- total_monthly_revenue
- average_revenue_per_user
- country_rank
- previous_country_average_revenue
- revenue_gap

Monthly revenue for each user should be calculated as:

monthly_fee * (1 - discount_percent / 100.0)

Country metrics:

- users_count — number of users in the country
- total_monthly_revenue — total discounted monthly revenue
  generated by all users in the country
- average_revenue_per_user — average discounted monthly
  revenue per user in the country
- country_rank — country ranking based on average
  revenue per user
- previous_country_average_revenue — average revenue per
  user of the country ranked immediately above the current
  country
- revenue_gap — difference between the current country's
  average revenue per user and the previous country's
  average revenue per user

Include only countries with at least 20 users.

Rank countries by average_revenue_per_user in descending
order using RANK().

Use LAG() to retrieve the average revenue per user of the
previous country in the ranking.

For the first country in the ranking, where there is no
previous country, previous_country_average_revenue and
revenue_gap should be NULL.

Calculate revenue_gap as:

average_revenue_per_user
-
previous_country_average_revenue

Round monetary values and revenue_gap to 2 decimal places.

Sort the final result by country_rank in ascending order.

Display:

- country
- users_count
- total_monthly_revenue
- average_revenue_per_user
- country_rank
- previous_country_average_revenue
- revenue_gap

Topics:

- CTE
- JOIN
- GROUP BY
- COUNT
- SUM
- AVG
- HAVING
- RANK
- LAG
- Window Functions
- Calculated fields
- ROUND
- NULL
- ORDER BY
==========================================================
*/

WITH statistic_by_country AS (
SELECT
sc.country,
COUNT(*) AS users_count,
SUM(s.monthly_fee * (1 - (s.discount_percent / 100.0))) AS total_monthly_revenue,
AVG(s.monthly_fee * (1 - (s.discount_percent / 100.0))) AS average_revenue_per_user 
FROM starlink_customers sc
JOIN subscriptions s 
ON sc.unique_id = s.customer_id
GROUP BY sc.country 
HAVING COUNT(*) >= 20
),
rank_by_country AS (
SELECT *,
RANK() OVER (
ORDER BY average_revenue_per_user DESC 
) AS country_rank
FROM statistic_by_country
),
lag_by_country AS (
SELECT *,
LAG(average_revenue_per_user) OVER(
ORDER BY average_revenue_per_user DESC 
) AS previous_country_average_revenue
FROM rank_by_country 
)
SELECT 
country,
users_count,
total_monthly_revenue,
ROUND(average_revenue_per_user,2) AS average_revenue_per_user,
country_rank,
ROUND(previous_country_average_revenue,2) AS previous_country_average_revenue,
ROUND((average_revenue_per_user - previous_country_average_revenue),2) AS revenue_gap
FROM lag_by_country  
ORDER BY country_rank ASC



























