/*
==========================================================
Project: SQL Practice – Starlink Analytics
Task: ST-565

Title:
Customer Revenue Segmentation

Author:
Pavlo Kotenko

Version:
1.0

Description:

Calculate the total subscription revenue generated by each
customer and classify customers into revenue segments.

Revenue should be calculated after applying the subscription
discount.

Display:

- Customer ID
- Customer full name
- Number of subscriptions
- Total revenue after discount
- Average revenue per subscription
- Revenue segment

Revenue segments:

- 'Low Revenue'      — total revenue < 100
- 'Medium Revenue'   — total revenue >= 100 and < 300
- 'High Revenue'     — total revenue >= 300

Requirements:

- Join starlink_customers with subscriptions.
- Combine customer's first and last name into a full name.
- Group data by customer.
- Count the number of subscriptions for each customer.
- Calculate total revenue after discount.
- Calculate average revenue per subscription.
- Use CASE to assign each customer to a revenue segment.
- Round revenue values to two decimal places in the final SELECT.
- Include customers who have subscriptions.
- Sort the result by total revenue after discount
  in descending order.

Topics:

- JOIN
- GROUP BY
- COUNT()
- SUM()
- CASE WHEN
- Revenue calculations
- String concatenation
- Aggregation
- Customer segmentation
- Rounding
- ORDER BY

==========================================================
*/

WITH subscription_data AS (
SELECT
s.customer_id,
sc.first_name,
sc.last_name,
s.subscription_id,
s.monthly_fee,
s.discount_percent,
(s.monthly_fee * (1 - (s.discount_percent / 100.0))) AS revenue_after_discount
FROM starlink_customers sc
JOIN subscriptions s
ON sc.unique_id = s.customer_id
),
customer_revenue AS (
SELECT
customer_id,
first_name,
last_name,
COUNT(*) AS subscriptions_count,
SUM(revenue_after_discount ) AS total_revenue,
AVG(revenue_after_discount ) AS avg_revenue
FROM subscription_data
GROUP BY customer_id, first_name, last_name 
),
customer_segmentation AS (
SELECT *,
CASE 
WHEN total_revenue   >= 300 THEN "High Revenue"
WHEN total_revenue   > 100 THEN "Medium Revenue"
ELSE "Low Revenue"
END AS revenue_segment
FROM customer_revenue
)
SELECT
customer_id,
(first_name || ' ' || last_name) AS full_name,
subscriptions_count,
ROUND(total_revenue , 2) AS total_revenue,
ROUND(avg_revenue , 2) AS avg_revenue,
revenue_segment 
FROM customer_segmentation





