/*
==========================================================
Project: SQL Practice – Starlink Analytics
Task: ST-547

Title:
Revenue Contribution by Plan

Author:
Pavlo Kotenko

Version:
1.0

Description:

Analyze the contribution of each subscription plan to the
total monthly revenue of its country.

For each combination of country and subscription plan,
calculate:

1. Number of users.
2. Total monthly revenue generated by the plan.
3. Total monthly revenue generated by the country.
4. Percentage contribution of the plan to the country's
   total revenue.
5. Revenue rank of the plan within the country.

Monthly revenue:

monthly_fee * (1 - discount_percent / 100.0)

Plan monthly revenue:

SUM(monthly_revenue) for each country and plan.

Country total revenue:

SUM(monthly_revenue) for all users within the country.

Plan revenue share:

plan_monthly_revenue / country_total_revenue * 100

Revenue rank:

Rank subscription plans within each country by
plan_monthly_revenue in descending order.

Plans with the same revenue must receive the same rank.

Filter:

Return only plans that contribute at least 30% of the
total monthly revenue of their country.

Display:

- country
- plan_name
- users_count
- plan_monthly_revenue
- country_total_revenue
- plan_revenue_share_percent
- revenue_rank

Round revenue and percentage values to 2 decimal places.

Sort the final results by:

1. country ASC
2. revenue_rank ASC

Topics:

- CTE
- JOIN
- GROUP BY
- COUNT()
- SUM()
- RANK()
- PARTITION BY
- ORDER BY
- Percentage Calculations
- Conditional Filtering
- ROUND()
- WHERE

==========================================================
*/

WITH user_statistic_by_plan AS (
SELECT
sc.country,
s.plan_name,
COUNT(*) AS users_count,
SUM(s.monthly_fee * (1 - s.discount_percent / 100.0)) AS plan_monthly_revenue 
FROM starlink_customers sc 
JOIN subscriptions s 
ON sc.unique_id = s.customer_id
GROUP BY sc.country, s.plan_name 
),
total_revenue_by_country AS (
SELECT 
sc.country,
SUM(s.monthly_fee * (1 - s.discount_percent / 100.0)) AS country_total_revenue 
FROM starlink_customers sc
JOIN subscriptions s
ON sc.unique_id = s.customer_id
GROUP BY country 
),
comparisson_tariff_by_total_revenue AS (
SELECT *,
((u.plan_monthly_revenue / t.country_total_revenue) * 100.0) AS plan_revenue_share_percent 
FROM user_statistic_by_plan u
INNER JOIN total_revenue_by_country t
ON u.country = t.country 
)
SELECT
country,
plan_name,
users_count,
plan_monthly_revenue,
country_total_revenue,
ROUND(plan_revenue_share_percent,2) AS plan_revenue_share_percent,
RANK() OVER (
PARTITION BY country
ORDER BY plan_monthly_revenue DESC
) AS revenue_rank
FROM comparisson_tariff_by_total_revenue 
WHERE plan_revenue_share_percent >= 30










