/*
==========================================================
Project: SQL Practice – Starlink Analytics
Task: ST-540

Title:
Country Revenue Contribution

Author:
Pavlo Kotenko

Version:
1.0

Description:

Analyze the contribution of each country to the total
monthly revenue generated by all Starlink customers.

For each country, calculate:

1. Number of users.
2. Total monthly revenue generated by the country.
3. Average monthly revenue per user.
4. Global total monthly revenue across all countries.
5. Percentage contribution of the country to global revenue.

Monthly revenue per user:

monthly_fee * (1 - discount_percent / 100.0)

Total country revenue:

SUM(monthly_revenue)

Average revenue per user:

total_country_revenue / users_count

Global monthly revenue:

SUM(monthly_revenue) across all customers.

Revenue share percentage:

total_country_revenue / global_monthly_revenue * 100

Only include countries whose contribution to global
monthly revenue is greater than 10%.

Display:

- country
- users_count
- total_monthly_revenue
- average_revenue_per_user
- global_monthly_revenue
- revenue_share_percentage

Round monetary values and percentage values to 2 decimal
places.

Sort the final results by revenue_share_percentage
in descending order.

Topics:

- CTE
- JOIN
- CROSS JOIN
- GROUP BY
- COUNT()
- SUM()
- ROUND()
- Global Aggregations
- Calculated Fields
- Percentage Calculations
- WHERE

==========================================================
*/ 

WITH revenue_per_country AS (
SELECT
sc.country,
COUNT(*) AS users_count,
SUM((s.monthly_fee * (1 - s.discount_percent / 100.0))) AS total_monthly_revenue,
ROUND(AVG((s.monthly_fee * (1 - s.discount_percent / 100.0))),2) AS average_revenue_per_user
FROM starlink_customers sc
JOIN subscriptions s 
ON sc.unique_id = s.customer_id
GROUP BY sc.country
),
total_revenue_by_all_countries AS (
SELECT
SUM((s.monthly_fee * (1 - s.discount_percent / 100.0))) AS global_monthly_revenue
FROM subscriptions s 
)
SELECT
country,
users_count,
total_monthly_revenue,
average_revenue_per_user,
global_monthly_revenue,
ROUND((total_monthly_revenue / global_monthly_revenue) * 100.0,2) AS revenue_share_percentage
FROM revenue_per_country 
CROSS JOIN total_revenue_by_all_countries
WHERE revenue_share_percentage > 10
ORDER BY revenue_share_percentage DESC









