/*
==========================================================
Project: SQL Practice – Starlink Analytics
Task: ST-548

Title:
Country Revenue Efficiency

Author:
Pavlo Kotenko

Version:
1.0

Description:

Determine which countries generate monthly revenue most
efficiently per user compared to the global average.

For each country calculate:

- country
- users_count
- total_monthly_revenue
- average_revenue_per_user
- global_average_revenue_per_user
- revenue_difference
- revenue_vs_global_percent

Monthly revenue for each user should be calculated as:

monthly_fee * (1 - discount_percent / 100.0)

Country metrics:

- users_count — number of users in the country
- total_monthly_revenue — total discounted monthly revenue
  generated by all users in the country
- average_revenue_per_user — total country revenue divided
  by the number of users
- global_average_revenue_per_user — average discounted
  monthly revenue per user across the entire dataset
- revenue_difference — country average revenue minus global
  average revenue
- revenue_vs_global_percent — percentage difference between
  country average revenue and global average revenue

Include only countries that:

- have at least 20 users
- have an average revenue per user above the global average

Sort the final result by revenue_vs_global_percent
in descending order.

Round monetary and percentage values to 2 decimal places.

Display:

- country
- users_count
- total_monthly_revenue
- average_revenue_per_user
- global_average_revenue_per_user
- revenue_difference
- revenue_vs_global_percent

Topics:

- CTE
- JOIN
- GROUP BY
- COUNT
- SUM
- AVG
- CROSS JOIN
- Calculated fields
- Percentage calculation
- WHERE
- ROUND
- Filtering
- Sorting
==========================================================
*/

WITH user_statistic AS (
SELECT 
sc.country,
COUNT(*) AS users_count,
SUM(s.monthly_fee * (1 - (s.discount_percent / 100.0))) AS total_monthly_revenue,
AVG(s.monthly_fee * (1 - (s.discount_percent / 100.0))) AS average_revenue_per_user
FROM starlink_customers sc
JOIN subscriptions s 
ON sc.unique_id = s.customer_id
GROUP BY sc.country
),
global_average_calculation AS (
SELECT
AVG((s.monthly_fee * (1 - (s.discount_percent / 100.0)))) AS global_average_revenue_per_user
FROM subscriptions s  
)
SELECT
country,
users_count,
total_monthly_revenue,
ROUND(average_revenue_per_user,2) AS average_revenue_per_user,
ROUND(global_average_revenue_per_user,2) AS global_average_revenue_per_user,
ROUND((average_revenue_per_user - global_average_revenue_per_user),2) AS revenue_difference,
ROUND(((average_revenue_per_user - global_average_revenue_per_user) / global_average_revenue_per_user * 100.0),2) AS revenue_vs_global_percent
FROM user_statistic 
CROSS JOIN global_average_calculation 
WHERE users_count >= 20 AND average_revenue_per_user > global_average_revenue_per_user 
ORDER BY revenue_vs_global_percent DESC



























